function env(n){return String(process.env[n]||'').trim()}
function out(res,s,b){res.status(s).setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(b))}
async function read(r){const t=await r.text();try{return t?JSON.parse(t):{}}catch(_){return{message:t||`HTTP ${r.status}`}}}
function q(v){return encodeURIComponent(String(v==null?'':v))}
function roleOf(v){v=String(v||'').trim().toLowerCase();if(v==='direktur'||v==='direktur utama')return'direksi';if(v==='mgmt'||v==='manajemen')return'management';if(v==='koord'||v==='coordinator')return'koordinator';return v}
function monthStart(v){const m=/^(\d{4})-(\d{2})(?:-\d{2})?$/.exec(String(v||''));if(!m)throw new Error('month wajib YYYY-MM');const n=Number(m[2]);if(n<1||n>12)throw new Error('month tidak valid');return `${m[1]}-${m[2]}-01`}
async function sbFetch(path,opts={}){const url=env('SUPABASE_URL'),svc=env('SUPABASE_SERVICE_ROLE_KEY');if(!url||!svc)throw new Error('Supabase server env missing');const r=await fetch(url+path,{...opts,headers:{apikey:svc,Authorization:`Bearer ${svc}`,'Content-Type':'application/json',...(opts.headers||{})}});const body=await read(r);if(!r.ok)throw new Error(body.message||body.error||`Supabase HTTP ${r.status}`);return body}
async function actor(req){const url=env('SUPABASE_URL'),pub=env('SUPABASE_PUBLISHABLE_KEY');if(!url||!pub)throw new Error('Supabase public env missing');const bearer=String(req.headers.authorization||'');if(!bearer.startsWith('Bearer '))throw new Error('Session required');const ur=await fetch(`${url}/auth/v1/user`,{headers:{apikey:pub,Authorization:bearer}}),u=await read(ur);if(!ur.ok||!u?.id)throw new Error('Session invalid');const rows=await sbFetch(`/rest/v1/user_profiles?id=eq.${q(u.id)}&select=id,email,full_name,role,staff_id,branch_id,is_active&limit=1`),p=rows?.[0];if(!p?.is_active)throw new Error('Profil tidak aktif');p.role=roleOf(p.role);return{user:u,profile:p}}
function requireRead(p){if(!['admin','direksi','management','koordinator'].includes(p.role))throw new Error('Role tidak boleh akses SOETA KPI')}
function requireWrite(p){if(!['admin','direksi','management'].includes(p.role))throw new Error('Hanya Admin/Direksi/Management boleh mengubah SOETA KPI')}
async function snapshot(req,p){requireRead(p);const staffId=String(req.query.staff_id||'').trim();if(!/^[0-9a-f-]{36}$/i.test(staffId))throw new Error('staff_id UUID wajib');const month=monthStart(req.query.month);const body=await sbFetch('/rest/v1/rpc/raos_soeta_kpi_staff_snapshot',{method:'POST',body:JSON.stringify({p_staff_id:staffId,p_month:month})});return{snapshot:body}}
async function manualUpsert(req,p){requireWrite(p);const b=req.body||{},staffId=String(b.staff_id||'').trim(),month=monthStart(b.month);if(!/^[0-9a-f-]{36}$/i.test(staffId))throw new Error('staff_id UUID wajib');const score=(name)=>{const v=b[name];if(v==null||v==='')return null;const n=Number(v);if(!Number.isFinite(n)||n<0||n>100)throw new Error(`${name} wajib 0-100`);return n};const row={staff_id:staffId,effective_month:month,sop_score:score('sop_score'),coaching_score:score('coaching_score'),coordinator_score:score('coordinator_score'),notes:String(b.notes||'').trim()||null,updated_by:p.id,updated_at:new Date().toISOString()};const saved=await sbFetch('/rest/v1/raos_soeta_kpi_manual_inputs?on_conflict=staff_id,effective_month',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(row)});return{row:saved?.[0]||row}}
function normEmail(v){return String(v||'').trim().toLowerCase()}
async function reconciliation(p){if(!['admin','direksi','management'].includes(p.role))throw new Error('Role tidak boleh melihat reconciliation');const employees=await sbFetch('/rest/v1/employees?branch=ilike.*Soeta*&select=employee_id,full_name,email,phone,branch,position,status,company_code,join_date&order=full_name.asc&limit=500');const master=await sbFetch('/rest/v1/raos_staff_master?airport=eq.SOETA&select=staff_id,full_name,email,phone,terminal,role,status,is_activated,auth_user_id,branch_id&order=full_name.asc&limit=500');const byId=new Map((master||[]).map(x=>[String(x.staff_id||'').toUpperCase(),x]));const byEmail=new Map((master||[]).filter(x=>normEmail(x.email)).map(x=>[normEmail(x.email),x]));const rows=(employees||[]).map(e=>{let m=byId.get(String(e.employee_id||'').toUpperCase())||null,match_method=m?'employee_id':null;if(!m&&normEmail(e.email)){m=byEmail.get(normEmail(e.email))||null;if(m)match_method='email'}return{employee:e,master:m,matched:!!m,match_method,needs_terminal:!m?.branch_id,needs_auth:!m?.auth_user_id}});return{rows,summary:{employees:rows.length,matched:rows.filter(x=>x.matched).length,unmatched:rows.filter(x=>!x.matched).length,needs_terminal:rows.filter(x=>x.needs_terminal).length,needs_auth:rows.filter(x=>x.needs_auth).length},read_only:true}}
module.exports=async function handler(req,res){try{const a=await actor(req),mode=String(req.query.mode||req.body?.mode||'');if(req.method==='GET'&&mode==='snapshot')return out(res,200,{success:true,...await snapshot(req,a.profile)});if(req.method==='GET'&&mode==='reconciliation')return out(res,200,{success:true,...await reconciliation(a.profile)});if(req.method==='POST'&&mode==='manual_upsert')return out(res,200,{success:true,...await manualUpsert(req,a.profile)});return out(res,404,{success:false,message:'Mode tidak dikenal'})}catch(e){return out(res,400,{success:false,message:e instanceof Error?e.message:String(e)})}}
